- alias: Turn on light when sun sets
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -2.5
  action:
    service: homeassistant.turn_on
    entity_id: group.back_porch_light

- alias: Turn off light when sun rises
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -2.5
  action:
    service: homeassistant.turn_off
    entity_id: group.back_porch_light

- alias: "Minimote Button 1 Pressed"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_8
      scene_id: 1
  action:
    service: switch.toggle
    entity_id: switch.christmas_lights
- alias: "Minimote Button 1 Pressed"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_12
      scene_id: 1
  action:
    service: switch.toggle
    entity_id: switch.christmas_lights
