homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml

frontend:
history:
logbook:
sun:
updater:
discovery:
conversation:
emulated_hue:
  host_ip: !secret homeassistant_ip

device_tracker:
  - platform: owntracks
#  - platform: nmap_tracker
#    hosts: 192.168.1.1/24
  - platform: snmp
    host: !secret router_host
    community: !secret router_snmp_community
    baseoid: !secret router_snmp_oid

http:
  api_password: !secret http_api_password

wemo:
  static:
    - !secret wemo1_host

light:
  - platform: hue
    allow_unreachable: true
    host: !secret hue_host

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

automation: !include_dir_merge_list automations/
group: !include_dir_merge_named groups/
media_player: !include media_players.yaml
sensor: !include_dir_merge_list sensors/
script: !include scripts.yaml
switch: !include switches.yaml
zone: !include zones.yaml
zwave: !include zwave.yaml
