homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml

frontend:
history:
logbook:
sun:
updater:
discovery:
conversation:
emulated_hue:
  host_ip: !secret homeassistant_ip

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
  - platform: snmp
    host: 192.168.1.1
    community: unicornutopia
    baseoid: 1.3.6.1.2.1.4.22.1.2

http:
  api_password: !secret http_api_password

wemo:
  static:
    - !secret wemo1_host

light:
  - platform: hue
    allow_unreachable: true
    host: !secret hue_host

sensor:
  - platform: steam_online
    api_key: !secret steam_api_key
    accounts:
      - !secret steam_account_id_1
  - platform: yr
    monitored_conditions:
      - temperature
  - platform: template
    sensors:
      solar_angle:
        value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
        friendly_name: 'Sun Angle'
        unit_of_measurement: '°'

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

switch:
  - platform: wake_on_lan
    mac_address: !secret joe_desktop_mac
    name: "Joe W-O-L"
    host: !secret joe_desktop_host

automation: !include automation.yaml
group: !include groups.yaml
script: !include scripts.yaml
zone: !include zones.yaml
zwave: !include zwave.yaml
