## switches.yaml

- platform: wake_on_lan
  mac_address: !secret joe_desktop_mac
  name: "Joe's Desktop"
  host: !secret joe_desktop_host

- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  timeout: 15
  switches:
    curtains:
      friendly_name: "Curtain Motor"
      command_on: 'sgCeAQsYCxgYCwwYCxcYDBcMCxgLGAsYCxgMFxgLDBcMFxgMCxgXDBgLDBcMFxgMFwwXDAsYCxgXDAwXDBcMGAsYFwwLGAwXDBgXDAsYCxgLGBcMnTEMGAsYFwwMFwwXGAsYDAsYCxgLGAsYCxgXDAwXDBgXDAsYFwwXDAwXDBcYDBcLGAwLGAsYFwwLGQsXDBcMFxgMCxgLGAwXGAsMGAsXDBgXDZwyCxgMFxgMCxgLGBcMFwwLGAsYDBgLGAsYFwwLGAsYFwwLGBcNFwwLGAsYFwwXDBcNCxcMGBcMCxgLGAsYCxgXDAsYDBgLGBcMFwwXDBcMCwABCJ0yCxgLGBcMCxgLGBcMFwwLGAwYCxgLGAsYFwwLGAsYFwwMGBcMFwwLGAsYFwwXDBcNCxgLGBcMCxgLGAsYCxgYDAsYCxgLGBcMFwwXDBcMDAABB50yCxgLGBcMCxgMFxgMFwwLGAsYCxgLGAsYFwwMFwwXGAwLGBcMFwwLGAwYFwwXDBcMCxgLGBcMCxgMFwwXDBgXDAsYCxgLGBgLGAwXDBcMCwAF3AAAAAAAAAAAAAA='
      command_off: 'sgAWAxcMGAsMGAsYFwwXDBcMDBcMFxcMDBcMFwwYCxgXDAwXDBcYDBcMCxgLGBcMF/6cMgsYCxgXDAwXDBcYCxgLDBgLGAsYCxgMFxgLDBgLGBcMCxgXDBgLCxgMFxgMFwwXDAsYCxgXDAwXDBcMGAsYFwwLGAwXGAsXDAwXDBcYDBcMnTILGAsYFwwLGAwXFwwYCwwYCxgLGAsYDBcYCwwXDBcYDAsYFwwXDAwXDBcYCxgLGAwLGAsYFwwMFwwXDBcMFxgMCxgLGBcMFwwMFwwXGAsY/Z0xDBgLGBcMCxgMFxgLGAsMGAsYCxgLGAsYFwwLGAwXFw0LFxgMFwwMFwsYGAsYCxgMCxgLGBcMCxgLGAwXDBcYDAsYCxgXDBcMDBcMFxgMFwydMQwYCxgXDAsYCxgYCxgLDBcMFwwXDBgLGBcMCxgLGBcMDBcYCxgMCxgLGBcMGAsXDQsYCxgXDAsYCxgLGAwXGAsMFwwYFwwXDAsYCxgXDBj9nTEMFwwXGAwLFwwYFwwXDAsYDBcMFwwYCxcYDAsYCxgXDAwXGAsYCwwYCxgXDBcMFwwMFwwXGAsMGAsYCxgLGBgMCxgLGBcMFwwLGAsYFwwXDZ0xDBcMFxgLDBgLGBcMFwwLGAsYCxgMGAsXGAwLGAsYFwwMFxcMGAsMFwwYFwwXDBcMCxgLGBgMCxgLGAsYCxgXDAwXDBcYDBcMCxgLGBcMFw2dMgsYCxgXDAsYDBcXDBgLDBcMGAsYCxgLGBcMDBcMFxgMCxgXDBcMCxgLGBgLGAsYDAsXDBgXDAsYCxgMFwwXGAwLGAsYFwwXDBgLGAsMFwwAAQicMgsYCxgXDAwXCxgYDBcMCxgLGAwXCxgLGBgLDBcMGBcMCxgXDBcMDBcLGBgMFwwXDAsYCxgXDAwXDBcMFwwYFwwLGAwXFwwYCxgLGAwLGAsAAQicMgwXDBcYCwwYCxgXDBcMCxgMFwsYDBgLFxgMCxcMGBcMDBcYDBcMCxgLFxgMFwwXDAsYCxgYDAsXDBgLGAsYFwwMFwwXGAsYDBcMFwwLGAsABdwMFw=='
