- platform: template
  sensors:
    status_smoke_co_alarm:
      value_template: >-
          {%- if is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_15_0", "13") %}
              Idle
          {%- elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_15_0", "1") %}
              Fire Detected
          {%- elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_15_0", "2") %}
              Carbon Monoxide Detected
          {%- elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_15_0", "12") %}
              Alarm Testing
          {% else %}
              Unknown
          {%- endif %}
      friendly_name: 'Smoke/CO Alarm'
    battery_level_smoke_co_alarm:
      value_template: '{{states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_15_0.attributes.battery_level}}'
      friendly_name: 'Smoke/CO Alarm Battery'
      unit_of_measurement: '%'
