- alias: Turn on light when sun sets
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -2.5
  action:
    service: homeassistant.turn_on
    entity_id: group.back_porch_light

- alias: Turn off light when sun rises
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -2.5
  action:
    service: homeassistant.turn_off
    entity_id: group.back_porch_light
